[package]
name = "nostr-rs-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
tokio = { version = "1.14.0", features = ["full"] }
futures-util = "0.3.17"
tokio-tungstenite = "0.16.0"
tungstenite = "0.16.0"
thiserror = "1.0.30"
