# Nostr-rs-relay configuration

[info]
# The advertised URL for the Nostr websocket.
relay_url = "wss://nostr.example.com/"

# Relay information for clients.  Put your unique server name here.
name = "nostr-rs-relay"

# Description
description = "A newly created nostr-rs-relay.\n\nCustomize this with your own info."

# Administrative contact pubkey
#pubkey = "0c2d168a4ae8ca58c9f1ab237b5df682599c6c7ab74307ea8b05684b60405d41"

# Administrative contact URI
#contact = "mailto:contact@example.com"

[database]
# Directory for SQLite files.  Defaults to the current directory.  Can
# also be specified (and overriden) with the "--db dirname" command
# line option.
data_directory = "."

# Database connection pool settings:

# Minimum number of SQLite reader connections
#min_conn = 4

# Maximum number of SQLite reader connections
#max_conn = 128

[network]
# Bind to this network address
address = "0.0.0.0"

# Listen on this port
port = 8080

[options]
# Reject events that have timestamps greater than this many seconds in
# the future.  Defaults to rejecting anything greater than 30 minutes
# from the current time.
reject_future_seconds = 1800

[limits]
# Limit events created per second, averaged over one minute.  Must be
# an integer.  If not set (or set to 0), defaults to unlimited.
#messages_per_sec = 0

# Limit the maximum size of an EVENT message.  Defaults to 128 KB.
# Set to 0 for unlimited.
#max_event_bytes = 131072

# Maximum WebSocket message in bytes.  Defaults to 128 KB.
#max_ws_message_bytes = 131072

# Maximum WebSocket frame size in bytes.  Defaults to 128 KB.
#max_ws_frame_bytes = 131072

# Broadcast buffer size, in number of events.  This prevents slow
# readers from consuming memory.  Defaults to 4096.
#broadcast_buffer = 4096

# Event persistence buffer size, in number of events.  This provides
# backpressure to senders if writes are slow.  Defaults to 16.
#event_persist_buffer = 16
